### ISSUE TITLE
PyTorch Lightning example not working

### ISSUE THREAD

**Issue by jacanchaplais** [optuna/optuna-examples#14]
Downloading and running the PyTorch Lightning example fails for me. The error being thrown indicates that `trainer.callback_metrics` is an empty dictionary.

### Hardware
2x RTX 8000 GPUs

### Software
Python 3.8.10
PyTorch 1.7.1
PyTorch Lightning 1.3.1
Optuna 2.7.0

**Comment by jacanchaplais** [comment]
Closed because I noticed it's a duplicate of https://github.com/optuna/optuna/issues/1417

**Comment by nzw0301** [comment]
Let me summarise the points -- thank you @jacanchaplais for pointing out them.

1. The multi-GPUs training does not work due to [this error](https://github.com/optuna/optuna/issues/1417#issuecomment-842967188) -- rank 0 has only the attribute `val_acc ` and the others do not. if a machine has multiple-GPUs, the `pytorch_lightining_simple.py` uses all GPUs in [the current example](https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_lightning_simple.py#L137), so this error happens alwasy on a machine with multiple GPUs.
2. Are there any issues with PyTorch-lightning with DDP training? If so, it would be great to mention it as comments in the example code or the callback page.

**Comment by jacanchaplais** [comment]
When using TorchMetrics (written by the same developers are PyTorch Lightning), the metrics are automatically distributed between devices during steps, and collected at the end of each step and epoch. These are made available in the hooks for those events, see [TorchMetrics](https://torchmetrics.readthedocs.io/en/latest/pages/lightning.html). I don't know why they don't populate the same dictionary, might be an error on their part, but perhaps it could be solved by writing monitored metrics to a property of the model? Probably best to do something that doesn't rely too heavily on their API, as it appears to be developing rapidly.

**Comment by jacanchaplais** [comment]
> I suppose rank 0 has only the attribute `val_acc` and the others do not.

Also, I don't think the issue is due to which device the metrics are stored to, as the line which tries to access `trainer.callback_metrics['val_acc']`  is after the `trainer.fit()` method has completed execution, so I would have thought that the data would not be partitioned to specific devices (although I am new to GPU parallelism, so let me know if I'm wrong).

**Comment by jacanchaplais** [comment]
Submitted failure to populate `callback_metrics` as an [issue to PyTorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning/issues/7671), as I implemented with Ray[Tune] and ran into the same problem.
